"""updated tables with date

Revision ID: 184209266906
Revises: ae5b8f60deba
Create Date: 2021-06-02 17:06:50.469661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184209266906'
down_revision = 'ae5b8f60deba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'created_at')
    # ### end Alembic commands ###
