"""empty message

Revision ID: ae5b8f60deba
Revises: de3323d2f8d3
Create Date: 2021-06-02 11:58:35.847656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5b8f60deba'
down_revision = 'de3323d2f8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.alter_column('ingredients', 'recipe_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'created_at')
    # ### end Alembic commands ###
