"""added source url to recipe model

Revision ID: 61e08bf35e47
Revises: a7fd06d7a9b7
Create Date: 2021-06-07 21:46:42.931405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e08bf35e47'
down_revision = 'a7fd06d7a9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'source_url')
    # ### end Alembic commands ###
