"""removed images table

Revision ID: a7fd06d7a9b7
Revises: a8c876edf028
Create Date: 2021-06-04 16:11:16.114521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fd06d7a9b7'
down_revision = 'a8c876edf028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.add_column('recipes', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('servings', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'servings')
    op.drop_column('recipes', 'image_url')
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='images_recipe_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='images_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    # ### end Alembic commands ###
