"""update

Revision ID: da65f3703059
Revises: fcdad19ebb2d
Create Date: 2021-06-08 12:21:42.123461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da65f3703059'
down_revision = 'fcdad19ebb2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('method', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
