"""instructions

Revision ID: e7aae53eeb96
Revises: da65f3703059
Create Date: 2021-06-08 12:23:30.634989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aae53eeb96'
down_revision = 'da65f3703059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('method', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'method')
    # ### end Alembic commands ###
