"""recipe db update source

Revision ID: fcdad19ebb2d
Revises: 61e08bf35e47
Create Date: 2021-06-08 12:06:45.292912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdad19ebb2d'
down_revision = '61e08bf35e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'step_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructions', sa.Column('step_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
